// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqcu8CC0ZwiWDxIvI0a8p6XWdZjhoCjJM',
    appId: '1:1069228519389:web:5882a12203131cf8285034',
    messagingSenderId: '1069228519389',
    projectId: 'final-project-24c70',
    authDomain: 'final-project-24c70.firebaseapp.com',
    storageBucket: 'final-project-24c70.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6VknziPRFMrFpC3xTKkgQPC98Kpw4mu0',
    appId: '1:1069228519389:android:a11c182b95f608dd285034',
    messagingSenderId: '1069228519389',
    projectId: 'final-project-24c70',
    storageBucket: 'final-project-24c70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwUNbG2yPqg0fOz-DLIsU7JgcH12pmrtg',
    appId: '1:1069228519389:ios:daddf72e37075da6285034',
    messagingSenderId: '1069228519389',
    projectId: 'final-project-24c70',
    storageBucket: 'final-project-24c70.firebasestorage.app',
    iosBundleId: 'com.example.dopaFit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwUNbG2yPqg0fOz-DLIsU7JgcH12pmrtg',
    appId: '1:1069228519389:ios:daddf72e37075da6285034',
    messagingSenderId: '1069228519389',
    projectId: 'final-project-24c70',
    storageBucket: 'final-project-24c70.firebasestorage.app',
    iosBundleId: 'com.example.dopaFit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqcu8CC0ZwiWDxIvI0a8p6XWdZjhoCjJM',
    appId: '1:1069228519389:web:805899a44abc1348285034',
    messagingSenderId: '1069228519389',
    projectId: 'final-project-24c70',
    authDomain: 'final-project-24c70.firebaseapp.com',
    storageBucket: 'final-project-24c70.firebasestorage.app',
  );
}
